### ISSUE TITLE
utf8 text from docker stream is converted using str bad!

### ISSUE THREAD

**Issue by bpmweel** [nlesc-sherlock/boatswain#3]
```
Traceback (most recent call last):
  File "/home/bweel/anaconda2/bin/boatswain", line 11, in <module>
    sys.exit(main())
  File "/home/bweel/anaconda2/lib/python2.7/site-packages/boatswain/cli.py", line 134, in main
    verbose=arguments.verbose, force=arguments.force)
  File "/home/bweel/anaconda2/lib/python2.7/site-packages/boatswain/boatswain.py", line 159, in build_up_to
    force=force, verbose=verbose)
  File "/home/bweel/anaconda2/lib/python2.7/site-packages/boatswain/boatswain.py", line 184, in build_up_to_dict
    force=force, verbose=verbose)
  File "/home/bweel/anaconda2/lib/python2.7/site-packages/boatswain/boatswain.py", line 210, in _process_up_to_dict
    force=force, verbose=verbose)
  File "/home/bweel/anaconda2/lib/python2.7/site-packages/boatswain/boatswain.py", line 246, in build_list
    verbose=verbose):
  File "/home/bweel/anaconda2/lib/python2.7/site-packages/boatswain/boatswain.py", line 315, in build_one
    ident = self._docker_progress(name, generator, verbose=verbose)
  File "/home/bweel/anaconda2/lib/python2.7/site-packages/boatswain/boatswain.py", line 460, in _docker_progress
    print(bcolors.blue(line), end="")
  File "/home/bweel/anaconda2/lib/python2.7/site-packages/boatswain/bcolors.py", line 13, in blue
    return bcolors._wrap(bcolors.OKBLUE, string)
  File "/home/bweel/anaconda2/lib/python2.7/site-packages/boatswain/bcolors.py", line 41, in _wrap
    return color + str(string) + bcolors.ENDC
UnicodeEncodeError: 'ascii' codec can't encode characters in position 53-55: ordinal not in range(128)

```

**Comment by bpmweel** [comment]
Fixed with e3d27248b920e90ed7b360d093a6ea8f157bac90
